Repository tejuamirthi/CustomDropDown, pull requests merged in 2020-10, with the labels that each got.

#15 Labelheight
  .DS_Store
  .gitignore
  CustomDropDown/View/CustomDropDown.swift
  Example/ViewController.swift
Labels: bug, hacktoberfest, hacktoberfest-accepted, user-interface

#11 image label cell
  .DS_Store
  CustomDropDown/Presenter/CustomDropDownPresenter.swift
  CustomDropDown/View/CustomDropDown.swift
  Example/ViewController.swift
Labels: enhancement, hacktoberfest-accepted, user-interface

#19 Refactor code
  CustomDropDown.xcodeproj/project.pbxproj
  CustomDropDown/Extensions/UIViewExtension.swift
  CustomDropDown/Model/DropDownConfig.swift
  CustomDropDown/Model/DropDownMode.swift
  CustomDropDown/Model/ImageLabelData.swift
  CustomDropDown/Presenter/CustomDropDownPresenter.swift
  CustomDropDown/Protocols/CustomDropDownDataSource.swift
  CustomDropDown/Protocols/CustomDropDownDelegate.swift
  CustomDropDown/Protocols/ViewCode.swift
  CustomDropDown/Support Files/CustomDropDown.h
  CustomDropDown/Support Files/Info.plist
  CustomDropDown/View/CustomDropDown.swift
  CustomDropDown/View/CustomDropDownView.swift
  CustomDropDown/View/DropDownDisplayView.swift
  CustomDropDown/View/DropDownImageLabelView.swift
Labels: documentation, good first issue, hacktoberfest

#24 Add shadow and corner radius to dropdown tableview.
  CustomDropDown.xcodeproj/project.pbxproj
  CustomDropDown/Model/DropDownConfig.swift
  CustomDropDown/Model/ShadowAndCornerConfig.swift
  CustomDropDown/View/CustomDropDown.swift
  CustomDropDown/View/CustomDropDownView.swift
  Example/ViewController.swift
Labels: enhancement, hacktoberfest-accepted, user-interface

#25 Add config dropDownCollapsable
  CustomDropDown/Model/DropDownConfig.swift
  CustomDropDown/View/CustomDropDownView.swift
Labels: enhancement, hacktoberfest

#18 Dropdown toggle
  CustomDropDown.xcodeproj/project.pbxproj
  CustomDropDown/Extensions/UIWindowExtension.swift
  CustomDropDown/View/CustomDropDownView.swift
Labels: bug, hacktoberfest, hacktoberfest-accepted, user-interface

#29 Feature/examples dropdown styles
  CustomDropDown.xcodeproj/project.pbxproj
  Example/Base.lproj/Main.storyboard
  Example/ImageLabelStyleViewController.swift
  Example/LabelStyleViewController.swift
Labels: enhancement, hacktoberfest, user-interface

#31 Handling reuse for tableview cell to resolve Overlap Text
  CustomDropDown/Presenter/CustomDropDownPresenter.swift
  CustomDropDown/View/CustomDropDownView.swift
  Example/Assets.xcassets/Contents.json
  Example/Assets.xcassets/football.imageset/Contents.json
  Example/Assets.xcassets/football.imageset/football.png
  Example/Assets.xcassets/rugby.imageset/Contents.json
  Example/Assets.xcassets/rugby.imageset/rugby-sport.png
  Example/LabelStyleViewController.swift
Labels: bug, hacktoberfest-accepted, user-interface
